// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mesh.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.meshtasticapp.protobufs;

@kotlin.jvm.JvmName("-initializedecoded")
public inline fun decoded(block: com.example.meshtasticapp.protobufs.DecodedKt.Dsl.() -> kotlin.Unit): com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.Decoded =
  com.example.meshtasticapp.protobufs.DecodedKt.Dsl._create(com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.Decoded.newBuilder()).apply { block() }._build()
/**
 * ```
 * This defines the "decoded" field inside MeshPacket
 * ```
 *
 * Protobuf type `Decoded`
 */
public object DecodedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.Decoded.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.Decoded.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.Decoded = _builder.build()

    /**
     * `.Decoded.PortNum portnum = 1;`
     */
    public var portnum: com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.Decoded.PortNum
      @JvmName("getPortnum")
      get() = _builder.portnum
      @JvmName("setPortnum")
      set(value) {
        _builder.portnum = value
      }
    public var portnumValue: kotlin.Int
      @JvmName("getPortnumValue")
      get() = _builder.portnumValue
      @JvmName("setPortnumValue")
      set(value) {
        _builder.portnumValue = value
      }
    /**
     * `.Decoded.PortNum portnum = 1;`
     */
    public fun clearPortnum() {
      _builder.clearPortnum()
    }

    /**
     * ```
     * Payload will be MeshData serialized as bytes
     * ```
     *
     * `bytes payload = 2;`
     */
    public var payload: com.google.protobuf.ByteString
      @JvmName("getPayload")
      get() = _builder.payload
      @JvmName("setPayload")
      set(value) {
        _builder.payload = value
      }
    /**
     * ```
     * Payload will be MeshData serialized as bytes
     * ```
     *
     * `bytes payload = 2;`
     */
    public fun clearPayload() {
      _builder.clearPayload()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.Decoded.copy(block: `com.example.meshtasticapp.protobufs`.DecodedKt.Dsl.() -> kotlin.Unit): com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.Decoded =
  `com.example.meshtasticapp.protobufs`.DecodedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

