// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mesh.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.meshtasticapp.protobufs;

@kotlin.jvm.JvmName("-initializemeshPacket")
public inline fun meshPacket(block: com.example.meshtasticapp.protobufs.MeshPacketKt.Dsl.() -> kotlin.Unit): com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket =
  com.example.meshtasticapp.protobufs.MeshPacketKt.Dsl._create(com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket.newBuilder()).apply { block() }._build()
/**
 * ```
 * The main packet sent over BLE / Radio
 * ```
 *
 * Protobuf type `MeshPacket`
 */
public object MeshPacketKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket = _builder.build()

    /**
     * `uint32 from = 1;`
     */
    public var from: kotlin.Int
      @JvmName("getFrom")
      get() = _builder.from
      @JvmName("setFrom")
      set(value) {
        _builder.from = value
      }
    /**
     * `uint32 from = 1;`
     */
    public fun clearFrom() {
      _builder.clearFrom()
    }

    /**
     * `uint32 to = 2;`
     */
    public var to: kotlin.Int
      @JvmName("getTo")
      get() = _builder.to
      @JvmName("setTo")
      set(value) {
        _builder.to = value
      }
    /**
     * `uint32 to = 2;`
     */
    public fun clearTo() {
      _builder.clearTo()
    }

    /**
     * `uint32 channel = 3;`
     */
    public var channel: kotlin.Int
      @JvmName("getChannel")
      get() = _builder.channel
      @JvmName("setChannel")
      set(value) {
        _builder.channel = value
      }
    /**
     * `uint32 channel = 3;`
     */
    public fun clearChannel() {
      _builder.clearChannel()
    }

    /**
     * `bool want_ack = 4;`
     */
    public var wantAck: kotlin.Boolean
      @JvmName("getWantAck")
      get() = _builder.wantAck
      @JvmName("setWantAck")
      set(value) {
        _builder.wantAck = value
      }
    /**
     * `bool want_ack = 4;`
     */
    public fun clearWantAck() {
      _builder.clearWantAck()
    }

    /**
     * ```
     * Either payload (raw) or decoded (preferred)
     * ```
     *
     * `bytes payload = 5;`
     */
    public var payload: com.google.protobuf.ByteString
      @JvmName("getPayload")
      get() = _builder.payload
      @JvmName("setPayload")
      set(value) {
        _builder.payload = value
      }
    /**
     * ```
     * Either payload (raw) or decoded (preferred)
     * ```
     *
     * `bytes payload = 5;`
     */
    public fun clearPayload() {
      _builder.clearPayload()
    }

    /**
     * `.Decoded decoded = 6;`
     */
    public var decoded: com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.Decoded
      @JvmName("getDecoded")
      get() = _builder.decoded
      @JvmName("setDecoded")
      set(value) {
        _builder.decoded = value
      }
    /**
     * `.Decoded decoded = 6;`
     */
    public fun clearDecoded() {
      _builder.clearDecoded()
    }
    /**
     * `.Decoded decoded = 6;`
     * @return Whether the decoded field is set.
     */
    public fun hasDecoded(): kotlin.Boolean {
      return _builder.hasDecoded()
    }

    public val MeshPacketKt.Dsl.decodedOrNull: com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.Decoded?
      get() = _builder.decodedOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket.copy(block: `com.example.meshtasticapp.protobufs`.MeshPacketKt.Dsl.() -> kotlin.Unit): com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket =
  `com.example.meshtasticapp.protobufs`.MeshPacketKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacketOrBuilder.decodedOrNull: com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.Decoded?
  get() = if (hasDecoded()) getDecoded() else null

