// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mesh.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.meshtasticapp.protobufs;

@kotlin.jvm.JvmName("-initializemeshPacket")
public inline fun meshPacket(block: com.example.meshtasticapp.protobufs.MeshPacketKt.Dsl.() -> kotlin.Unit): com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket =
  com.example.meshtasticapp.protobufs.MeshPacketKt.Dsl._create(com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket.newBuilder()).apply { block() }._build()
/**
 * ```
 * Define the MeshPacket message that includes the MeshData
 * ```
 *
 * Protobuf type `MeshPacket`
 */
public object MeshPacketKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket = _builder.build()

    /**
     * ```
     * Optional field for command ID
     * ```
     *
     * `optional uint32 from = 1;`
     */
    public var from: kotlin.Int
      @JvmName("getFrom")
      get() = _builder.from
      @JvmName("setFrom")
      set(value) {
        _builder.from = value
      }
    /**
     * ```
     * Optional field for command ID
     * ```
     *
     * `optional uint32 from = 1;`
     */
    public fun clearFrom() {
      _builder.clearFrom()
    }
    /**
     * ```
     * Optional field for command ID
     * ```
     *
     * `optional uint32 from = 1;`
     * @return Whether the from field is set.
     */
    public fun hasFrom(): kotlin.Boolean {
      return _builder.hasFrom()
    }

    /**
     * ```
     * Recipient ID
     * ```
     *
     * `uint32 to = 2;`
     */
    public var to: kotlin.Int
      @JvmName("getTo")
      get() = _builder.to
      @JvmName("setTo")
      set(value) {
        _builder.to = value
      }
    /**
     * ```
     * Recipient ID
     * ```
     *
     * `uint32 to = 2;`
     */
    public fun clearTo() {
      _builder.clearTo()
    }

    /**
     * ```
     * Channel for the message
     * ```
     *
     * `uint32 channel = 3;`
     */
    public var channel: kotlin.Int
      @JvmName("getChannel")
      get() = _builder.channel
      @JvmName("setChannel")
      set(value) {
        _builder.channel = value
      }
    /**
     * ```
     * Channel for the message
     * ```
     *
     * `uint32 channel = 3;`
     */
    public fun clearChannel() {
      _builder.clearChannel()
    }

    /**
     * ```
     * Payload, which will be a MeshData message
     * ```
     *
     * `bytes payload = 4;`
     */
    public var payload: com.google.protobuf.ByteString
      @JvmName("getPayload")
      get() = _builder.payload
      @JvmName("setPayload")
      set(value) {
        _builder.payload = value
      }
    /**
     * ```
     * Payload, which will be a MeshData message
     * ```
     *
     * `bytes payload = 4;`
     */
    public fun clearPayload() {
      _builder.clearPayload()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket.copy(block: `com.example.meshtasticapp.protobufs`.MeshPacketKt.Dsl.() -> kotlin.Unit): com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket =
  `com.example.meshtasticapp.protobufs`.MeshPacketKt.Dsl._create(this.toBuilder()).apply { block() }._build()

