// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mesh.proto
// Protobuf Java Version: 4.29.3

package com.example.meshtasticapp.protobufs;

public final class MeshtasticappProtobufs {
  private MeshtasticappProtobufs() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      MeshtasticappProtobufs.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MeshDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MeshData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * This field will store the text message
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <pre>
     * This field will store the text message
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * <pre>
   * Define the MeshData message that contains a text string
   * </pre>
   *
   * Protobuf type {@code MeshData}
   */
  public static final class MeshData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MeshData)
      MeshDataOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        MeshData.class.getName());
    }
    // Use MeshData.newBuilder() to construct.
    private MeshData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MeshData() {
      text_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.internal_static_MeshData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.internal_static_MeshData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData.class, com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData.Builder.class);
    }

    public static final int TEXT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object text_ = "";
    /**
     * <pre>
     * This field will store the text message
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * This field will store the text message
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, text_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, text_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData)) {
        return super.equals(obj);
      }
      com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData other = (com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData) obj;

      if (!getText()
          .equals(other.getText())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Define the MeshData message that contains a text string
     * </pre>
     *
     * Protobuf type {@code MeshData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MeshData)
        com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.internal_static_MeshData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.internal_static_MeshData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData.class, com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData.Builder.class);
      }

      // Construct using com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        text_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.internal_static_MeshData_descriptor;
      }

      @java.lang.Override
      public com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData getDefaultInstanceForType() {
        return com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData build() {
        com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData buildPartial() {
        com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData result = new com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.text_ = text_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData) {
          return mergeFrom((com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData other) {
        if (other == com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData.getDefaultInstance()) return this;
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                text_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <pre>
       * This field will store the text message
       * </pre>
       *
       * <code>string text = 1;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * This field will store the text message
       * </pre>
       *
       * <code>string text = 1;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * This field will store the text message
       * </pre>
       *
       * <code>string text = 1;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        text_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * This field will store the text message
       * </pre>
       *
       * <code>string text = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        text_ = getDefaultInstance().getText();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * This field will store the text message
       * </pre>
       *
       * <code>string text = 1;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        text_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MeshData)
    }

    // @@protoc_insertion_point(class_scope:MeshData)
    private static final com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData();
    }

    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MeshData>
        PARSER = new com.google.protobuf.AbstractParser<MeshData>() {
      @java.lang.Override
      public MeshData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MeshData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MeshData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MeshPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MeshPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Optional field for command ID
     * </pre>
     *
     * <code>optional uint32 from = 1;</code>
     * @return Whether the from field is set.
     */
    boolean hasFrom();
    /**
     * <pre>
     * Optional field for command ID
     * </pre>
     *
     * <code>optional uint32 from = 1;</code>
     * @return The from.
     */
    int getFrom();

    /**
     * <pre>
     * Recipient ID
     * </pre>
     *
     * <code>uint32 to = 2;</code>
     * @return The to.
     */
    int getTo();

    /**
     * <pre>
     * Channel for the message
     * </pre>
     *
     * <code>uint32 channel = 3;</code>
     * @return The channel.
     */
    int getChannel();

    /**
     * <pre>
     * Payload, which will be a MeshData message
     * </pre>
     *
     * <code>bytes payload = 4;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * <pre>
   * Define the MeshPacket message that includes the MeshData
   * </pre>
   *
   * Protobuf type {@code MeshPacket}
   */
  public static final class MeshPacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MeshPacket)
      MeshPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        MeshPacket.class.getName());
    }
    // Use MeshPacket.newBuilder() to construct.
    private MeshPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MeshPacket() {
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.internal_static_MeshPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.internal_static_MeshPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket.class, com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket.Builder.class);
    }

    private int bitField0_;
    public static final int FROM_FIELD_NUMBER = 1;
    private int from_ = 0;
    /**
     * <pre>
     * Optional field for command ID
     * </pre>
     *
     * <code>optional uint32 from = 1;</code>
     * @return Whether the from field is set.
     */
    @java.lang.Override
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Optional field for command ID
     * </pre>
     *
     * <code>optional uint32 from = 1;</code>
     * @return The from.
     */
    @java.lang.Override
    public int getFrom() {
      return from_;
    }

    public static final int TO_FIELD_NUMBER = 2;
    private int to_ = 0;
    /**
     * <pre>
     * Recipient ID
     * </pre>
     *
     * <code>uint32 to = 2;</code>
     * @return The to.
     */
    @java.lang.Override
    public int getTo() {
      return to_;
    }

    public static final int CHANNEL_FIELD_NUMBER = 3;
    private int channel_ = 0;
    /**
     * <pre>
     * Channel for the message
     * </pre>
     *
     * <code>uint32 channel = 3;</code>
     * @return The channel.
     */
    @java.lang.Override
    public int getChannel() {
      return channel_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Payload, which will be a MeshData message
     * </pre>
     *
     * <code>bytes payload = 4;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, from_);
      }
      if (to_ != 0) {
        output.writeUInt32(2, to_);
      }
      if (channel_ != 0) {
        output.writeUInt32(3, channel_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(4, payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, from_);
      }
      if (to_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, to_);
      }
      if (channel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, channel_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket)) {
        return super.equals(obj);
      }
      com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket other = (com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket) obj;

      if (hasFrom() != other.hasFrom()) return false;
      if (hasFrom()) {
        if (getFrom()
            != other.getFrom()) return false;
      }
      if (getTo()
          != other.getTo()) return false;
      if (getChannel()
          != other.getChannel()) return false;
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFrom()) {
        hash = (37 * hash) + FROM_FIELD_NUMBER;
        hash = (53 * hash) + getFrom();
      }
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo();
      hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
      hash = (53 * hash) + getChannel();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Define the MeshPacket message that includes the MeshData
     * </pre>
     *
     * Protobuf type {@code MeshPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MeshPacket)
        com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.internal_static_MeshPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.internal_static_MeshPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket.class, com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket.Builder.class);
      }

      // Construct using com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        from_ = 0;
        to_ = 0;
        channel_ = 0;
        payload_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.internal_static_MeshPacket_descriptor;
      }

      @java.lang.Override
      public com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket getDefaultInstanceForType() {
        return com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket build() {
        com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket buildPartial() {
        com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket result = new com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.from_ = from_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.to_ = to_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.channel_ = channel_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.payload_ = payload_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket) {
          return mergeFrom((com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket other) {
        if (other == com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket.getDefaultInstance()) return this;
        if (other.hasFrom()) {
          setFrom(other.getFrom());
        }
        if (other.getTo() != 0) {
          setTo(other.getTo());
        }
        if (other.getChannel() != 0) {
          setChannel(other.getChannel());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                from_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                to_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                channel_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                payload_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int from_ ;
      /**
       * <pre>
       * Optional field for command ID
       * </pre>
       *
       * <code>optional uint32 from = 1;</code>
       * @return Whether the from field is set.
       */
      @java.lang.Override
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Optional field for command ID
       * </pre>
       *
       * <code>optional uint32 from = 1;</code>
       * @return The from.
       */
      @java.lang.Override
      public int getFrom() {
        return from_;
      }
      /**
       * <pre>
       * Optional field for command ID
       * </pre>
       *
       * <code>optional uint32 from = 1;</code>
       * @param value The from to set.
       * @return This builder for chaining.
       */
      public Builder setFrom(int value) {

        from_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional field for command ID
       * </pre>
       *
       * <code>optional uint32 from = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000001);
        from_ = 0;
        onChanged();
        return this;
      }

      private int to_ ;
      /**
       * <pre>
       * Recipient ID
       * </pre>
       *
       * <code>uint32 to = 2;</code>
       * @return The to.
       */
      @java.lang.Override
      public int getTo() {
        return to_;
      }
      /**
       * <pre>
       * Recipient ID
       * </pre>
       *
       * <code>uint32 to = 2;</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(int value) {

        to_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Recipient ID
       * </pre>
       *
       * <code>uint32 to = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        to_ = 0;
        onChanged();
        return this;
      }

      private int channel_ ;
      /**
       * <pre>
       * Channel for the message
       * </pre>
       *
       * <code>uint32 channel = 3;</code>
       * @return The channel.
       */
      @java.lang.Override
      public int getChannel() {
        return channel_;
      }
      /**
       * <pre>
       * Channel for the message
       * </pre>
       *
       * <code>uint32 channel = 3;</code>
       * @param value The channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannel(int value) {

        channel_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Channel for the message
       * </pre>
       *
       * <code>uint32 channel = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        channel_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Payload, which will be a MeshData message
       * </pre>
       *
       * <code>bytes payload = 4;</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <pre>
       * Payload, which will be a MeshData message
       * </pre>
       *
       * <code>bytes payload = 4;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        payload_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Payload, which will be a MeshData message
       * </pre>
       *
       * <code>bytes payload = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000008);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MeshPacket)
    }

    // @@protoc_insertion_point(class_scope:MeshPacket)
    private static final com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket();
    }

    public static com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MeshPacket>
        PARSER = new com.google.protobuf.AbstractParser<MeshPacket>() {
      @java.lang.Override
      public MeshPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MeshPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MeshPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MeshData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MeshData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MeshPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MeshPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmesh.proto\"\030\n\010MeshData\022\014\n\004text\030\001 \001(\t\"V" +
      "\n\nMeshPacket\022\021\n\004from\030\001 \001(\rH\000\210\001\001\022\n\n\002to\030\002 " +
      "\001(\r\022\017\n\007channel\030\003 \001(\r\022\017\n\007payload\030\004 \001(\014B\007\n" +
      "\005_fromB=\n#com.example.meshtasticapp.prot" +
      "obufsB\026MeshtasticappProtobufsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MeshData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MeshData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MeshData_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_MeshPacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MeshPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MeshPacket_descriptor,
        new java.lang.String[] { "From", "To", "Channel", "Payload", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
