// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mesh.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.meshtasticapp.protobufs;

@kotlin.jvm.JvmName("-initializemeshData")
public inline fun meshData(block: com.example.meshtasticapp.protobufs.MeshDataKt.Dsl.() -> kotlin.Unit): com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData =
  com.example.meshtasticapp.protobufs.MeshDataKt.Dsl._create(com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData.newBuilder()).apply { block() }._build()
/**
 * ```
 * Define the MeshData message that contains a text string
 * ```
 *
 * Protobuf type `MeshData`
 */
public object MeshDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData = _builder.build()

    /**
     * ```
     * This field will store the text message
     * ```
     *
     * `string text = 1;`
     */
    public var text: kotlin.String
      @JvmName("getText")
      get() = _builder.text
      @JvmName("setText")
      set(value) {
        _builder.text = value
      }
    /**
     * ```
     * This field will store the text message
     * ```
     *
     * `string text = 1;`
     */
    public fun clearText() {
      _builder.clearText()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData.copy(block: `com.example.meshtasticapp.protobufs`.MeshDataKt.Dsl.() -> kotlin.Unit): com.example.meshtasticapp.protobufs.MeshtasticappProtobufs.MeshData =
  `com.example.meshtasticapp.protobufs`.MeshDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

